spring:
    application:
        name: demo01-chat-client
    ai:
        dashscope:
            api-key: ${DASHSCOPE_API_KEY}
server:
    port: 8081

logging:
    level:
        org:
            springframework:
                ai:
                    chat:
                        client:
                            advisor: debug